Add macos text service
w3c/aria-at-automation-driver pull request #32
Opened 2024-01-10 05:53 UTC by mzgoddard

Depends on #30 and #31.

## Summary

Add an XPC Service, called `ATDriverGenericService`, to the xcode project. This service handles communication between the AudioUnit and the `lib/cli.js` nodejs executable. 

## Changes

- Add ATDriverGenericService to xcode project
- Add service build dependency to Extension
- Add unix socket path to cli.js
- Create directory for socket and unlink old leftover sockets in cli.js

## Description

XPC Services are useful for separating some work into another process. In this case this change uses a service to separate socket communication with a nodejs process. This way the blocking calls to bsd socket apis are done in a process other then the one the audio unit runs its synthesis in.

The extension creates an XPCConnection designating the target service and protocol. With that, the extension calls methods on a proxy with the same interface as the protocol. The methods queue messages to be sent. When the service is created and starts, it receives and processes those message. As implemented this service than produces messages in the format `cli.js` expects and opens a unix family socket to send the message.

### Adding an Service in Xcode

When adding the service Xcode added the service as a build dependency to the container application. For the extension to be able to use the service it has been added as a build dependency to the extension as well.

2024-01-10 06:13 UTC, mzgoddard commented on src/macos/ATDriverGenericMacOS/ATDriverGenericService/ATDriverClientUnix.swift
> +  class SocketResource {
Made this RAII type to automatically handle closing the socket. In the case of how its currently used, when the resource goes out of scope in `_sendEvent`, it'll de-initialize and close the socket. This way we don't have to be careful of all the edge cases around throw, return, and other scenarios of the socket left hanging open.

2024-01-10 16:39 UTC, mzgoddard commented
Some alternatives I considered before the XPCService and BSD socket approach here:
- Implementing a websocket server in swift/objc in place of cli.js for macos with https://github.com/facebookincubator/SocketRocket
- [NSSocketPort](https://developer.apple.com/documentation/foundation/nssocketport)
  - I'm not sure this can be used with node.js as the remote without adding a dependency on its side

2024-01-30 01:05 UTC, jugglinmike requested changes
I'm unable to build the project on my system; here's the error:

> Build input file cannot be found: '/Users/mike/projects/bocoup/facebook-aria/aria-at-automation-driver/src/macos/ATDriverGenericMacOS/ATDriverGenericService/ATDriverClientIP.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

I'll be happy to debug this with you on a call if that'd help, though it sounds we may just need to add a file from your machine. Let me know!

Separately, [it looks like macOS allows the app to write to a directory in `~/Library/Containers`.](https://developer.apple.com/documentation/xcode/configuring-the-macos-app-sandbox) Since this isn't included among [the alternatives you mentioned](https://github.com/w3c/aria-at-automation-driver/pull/32#issuecomment-1885206942), I'm wondering if it's worth exploring. Would it be viable to place the socket there so that the app could pass messages to the AT Driver server without the need for the daemon?

2024-01-30 02:05 UTC, jugglinmike commented
It looks like the references to "ATDriverClientIP.swift" are being removed in gh-33, so maybe we just need to cherry-pick those changes here...

2024-01-30 21:37 UTC, mzgoddard commented
> It looks like the references to "ATDriverClientIP.swift" are being removed in [gh-33](https://github.com/w3c/aria-at-automation-driver/pull/33), so maybe we just need to cherry-pick those changes here...

I think we can cherry-pick https://github.com/w3c/aria-at-automation-driver/pull/33/commits/97ef8e805665ca690772df0df88a4d565c3f28ec for the `...IP.swift` deletion and the signing change.

2024-01-30 23:14 UTC, mzgoddard commented on lib/cli.js
> +const WINDOWS_NAMED_PIPE = '\\\\?\\pipe\\my_pipe';
I'm not sure what a better name would be. https://learn.microsoft.com/en-us/windows/win32/ipc/named-pipes I'd have to go look up more about them. It's not a unix socket or local socket. I guess there is some kind of system server for pipes. The name isn't a path, just path-like. Windows doesn't create a file on the file system like a unix/local socket does.

Do you mean the `my_pipe` part?

2024-01-30 23:18 UTC, mzgoddard commented on lib/cli.js
> +const WINDOWS_NAMED_PIPE = '\\\\?\\pipe\\my_pipe';
`WINDOWS_PIPE_NAME` would have the same tense/phrasing that `MACOS_SOCKET_UNIX_PATH` has. Is that what you are thinking?

2024-01-31 16:28 UTC, mzgoddard commented on lib/cli.js
> +    await fs.unlink(MACOS_SOCKET_UNIX_PATH).catch(() => {});
Applied in #36.

2024-01-31 16:28 UTC, mzgoddard commented on lib/cli.js
> +  throw new Error(`unknown host platform '${process.platform}'`);
Applied in #36.

2024-01-31 16:29 UTC, mzgoddard commented
I cherry-picked the change from #33. You should be able to build and debug locally now.

I applied your requested changes to `cli.js` in its own PR, #36.

2024-01-31 22:51 UTC, jugglinmike commented on lib/cli.js
> +const WINDOWS_NAMED_PIPE = '\\\\?\\pipe\\my_pipe';
I mean that `at_driver_generic` would be far more descriptive than `my_pipe`. Now that this patch is blocked on the new one, I'll do this in a follow-up.

2024-01-31 22:52 UTC, jugglinmike commented
> I applied your requested changes to `cli.js` in its own PR, #36.

How come?

I've merged gh-36; could you rebase this?

2024-01-31 23:27 UTC, jugglinmike commented
Since this branch doesn't conflict with `main`, I was able to merge it locally for review purposes. However, the at-driver server doesn't report any text at all. I also tried validating using [the method from gh-33](https://github.com/w3c/aria-at-automation-driver/pull/33/files#diff-f9d3691e2393e19c508afc45d012a488979f01443d0b92f75903e1956b45857bR21), but that came up empty, too. Shouldn't both of these show the text that I pass into the `say` command?

Also, did you see [my question about `~/Library/Containers`](https://github.com/w3c/aria-at-automation-driver/pull/32#pullrequestreview-1850045720)?

2024-02-01 02:15 UTC, mzgoddard commented
> Also, did you see [my question about `~/Library/Containers`](https://github.com/w3c/aria-at-automation-driver/pull/32#pullrequestreview-1850045720)?

Yes, if we had the app sandbox enabled, we'd have to use a socket path in `~/Library/Containers`. We don't have sandbox enabled. We don't need to. Its required for publishing through the App Store, but we don't plan to do that.

The XPCService is used to parallelize communicating over a socket with nodejs. The parallelization is the key point I think. The alternatives I mentioned were for resolving the parallelization as well.

I think we want the socket communication to occur somehow on a different thread or process than the speech synthesis request. I don't know what kind of issues would happen if we didn't do that, but I think this is a good goal for making a reliable tool.

The XPCService handles a lot of parallelization issues for us, like race conditions and resource management.

2024-02-01 02:18 UTC, mzgoddard commented
> > I applied your requested changes to `cli.js` in its own PR, #36.
> 
> How come?
> 
> I've merged [gh-36](https://github.com/w3c/aria-at-automation-driver/pull/36); could you rebase this?

#36 helps test #35 and #37 together as well. I figured removing the socket path in this PR would make it easier to locally merge with #36 to test without rebasing #32 if we made further changes to #36. Sorry I didn't express that earlier.

I'll rebase.

2024-02-01 17:02 UTC, mzgoddard commented
> Since this branch doesn't conflict with `main`, I was able to merge it locally for review purposes. However, the at-driver server doesn't report any text at all. I also tried validating using [the method from gh-33](https://github.com/w3c/aria-at-automation-driver/pull/33/files#diff-f9d3691e2393e19c508afc45d012a488979f01443d0b92f75903e1956b45857bR21), but that came up empty, too. Shouldn't both of these show the text that I pass into the `say` command?

@jugglinmike You're probably encountering an issue with the solution using an Application Extension. The extension discovery method doesn't handle duplicates well. The safest way to test it would be with a new system like a virtual machine. Outside that you need to delete any duplicate extensions.

My first step for troubleshooting this kind of thing is to clean the build folder in Xcode, and wait a few minutes before rebuilding. If you have the extension selected in Spoken Content in System Settings you should select another speech synthesizer.

A hacky way you can test if its finding the latest build is to change the name in `ATDriverGenericMacOSExtensionAudioUnit.speechVoices`.

2024-02-06 02:28 UTC, jugglinmike commented
> I'll rebase.

After running with this new version of the branch, the `say` command exits with an error.

<details>
  <summary>expand to review the error message</summary>

```
$ say hello
2024-02-05 20:45:03.784 say[2052:16831] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000035ae620] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
    "en-US"
), Age: 0, Gender: 0, Size: 0, Version: (null)
2024-02-05 20:45:03.785 say[2052:16831] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000035ae620] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
    "en-US"
), Age: 0, Gender: 0, Size: 0, Version: (null)
2024-02-05 20:45:03.786 say[2052:16831] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000035ae620] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
    "en-US"
), Age: 0, Gender: 0, Size: 0, Version: (null)
2024-02-05 20:45:03.787 say[2052:16831] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000035ae620] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
    "en-US"
), Age: 0, Gender: 0, Size: 0, Version: (null)
2024-02-05 20:45:03.787 say[2052:16831] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000035ae620] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
    "en-US"
), Age: 0, Gender: 0, Size: 0, Version: (null)
2024-02-05 20:45:03.788 say[2052:16831] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000035ae620] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
    "en-US"
), Age: 0, Gender: 0, Size: 0, Version: (null)
```

</details>

> You're probably encountering an issue with the solution using an Application Extension. The extension discovery method doesn't handle duplicates well. The safest way to test it would be with a new system like a virtual machine.

If contributing to this project is going to require a virtual environment, we'll definitely need to document that in the contribution guidelines (ideally within the commit which introduces the requirement).

> Outside that you need to delete any duplicate extensions.

My research into your recommendation has identified the "Extension" section of macOS's System Preferences. While the audio unit is listed there, the associated UI is so vague (an unlabeled check box) that I can't infer what it actually does:

![image](https://github.com/w3c/aria-at-automation-driver/assets/677252/1969d247-83f7-4b1f-b3e2-2d30f088a828)

Unchecking a box seems like an unorthodox method to remove something, but I tried it, anyway. That didn't help.

Can you be a little more specific?

> A hacky way you can test if its finding the latest build is to change the name in `ATDriverGenericMacOSExtensionAudioUnit.speechVoices`.

I've interpreted your statement to mean, "modify the file `src/macos/ATDriverGenericMacOS/ATDriverGenericMacOSExtension/Common/Audio Unit/ATDriverGenericMacOSExtensionAudioUnit.swift`," however, that doesn't seem to be correct. There is no new voice listed after I applied the following change, cleaned the project, and ran the project again:

```diff
--- a/src/macos/ATDriverGenericMacOS/ATDriverGenericMacOSExtension/Common/Audio Unit/ATDriverGenericMacOSExtensionAudioUnit.swift       
+++ b/src/macos/ATDriverGenericMacOS/ATDriverGenericMacOSExtension/Common/Audio Unit/ATDriverGenericMacOSExtensionAudioUnit.swift       
@@ -167,7 +167,7 @@ public class ATDriverGenericMacOSExtensionAudioUnit: AVSpeechSynthesisProviderAu
                 logger.log("speechVoices")
             }
             return [
-            AVSpeechSynthesisProviderVoice(name: "ATDriverGenericMacOSExtensionVoice", identifier: "ATDriverGenericMacOSExtension", primaryLanguages: ["en-US"], supportedLanguages: ["en-US"])
+            AVSpeechSynthesisProviderVoice(name: "ATDriverGenericMacOSExtensionVoice2", identifier: "ATDriverGenericMacOSExtension2", primaryLanguages: ["en-US"], supportedLanguages: ["en-US"])
             ]
         }
         set { }
```

Can you be a little more specific?

2024-02-08 23:41 UTC, mzgoddard commented
> > I'll rebase.
> 
> After running with this new version of the branch, the `say` command exits with an error.
> expand to review the error message

Oh. Interesting. Can you dump `log show --process ATDriverGeneric`?

I'm thinking there are two high level possibiliities here:
- I introduced a bug and it tries to instantiate but fails.
- It's trying to instantiate the AudioUnit from a build that was deleted.

The second of those is a wild guess. I'm not sure its even possible.

Either way that log will hopefully give us clues.

> > You're probably encountering an issue with the solution using an Application Extension. The extension discovery method doesn't handle duplicates well. The safest way to test it would be with a new system like a virtual machine.
> 
> If contributing to this project is going to require a virtual environment, we'll definitely need to document that in the contribution guidelines (ideally within the commit which introduces the requirement).

That sounds good to me. I think we have been there from the beginning. Needing software installed or configuration changes at the user level on operating systems for it to be used by third party applications I think fulfills this. We can't have multiple installed copies of the voices.

> > Outside that you need to delete any duplicate extensions.
> 
> My research into your recommendation has identified the "Extension" section of macOS's System Preferences. While the audio unit is listed there, the associated UI is so vague (an unlabeled check box) that I can't infer what it actually does:
> 
> ![image](https://private-user-images.githubusercontent.com/677252/302482585-1969d247-83f7-4b1f-b3e2-2d30f088a828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MzE4MDcsIm5iZiI6MTcwNzQzMTUwNywicGF0aCI6Ii82NzcyNTIvMzAyNDgyNTg1LTE5NjlkMjQ3LTgzZjctNGIxZi1iM2UyLTJkMzBmMDg4YTgyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQyMjMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjI5YWE0MDBmYjJhODg1YmJlZTUwN2Y5YzlmNDU5NzdhNzQzN2E0YjFkNzlmNWY3YjRiN2M0NzhjYWExMDQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DdrWhgaUjlmRL-EmpBUOJj5_l7wd4iKVgwk1dzMX4Vg)
> 
> Unchecking a box seems like an unorthodox method to remove something, but I tried it, anyway. That didn't help.
> 
> Can you be a little more specific?

By delete I meant for you to delete the built files from the file system.

The screen you show toggles permission for the application extension by extension interface. The extensions you have installed in that screen both have `com.apple.AudioUnit` extensions. For example I have an application extension installed for Pixelmator Pro which contains multiple extension interfaces and can be toggled in part.

![image](https://github.com/w3c/aria-at-automation-driver/assets/833298/c48a13a8-5128-49e9-b91c-186ef59a4e4d)

> > A hacky way you can test if its finding the latest build is to change the name in `ATDriverGenericMacOSExtensionAudioUnit.speechVoices`.
> 
> I've interpreted your statement to mean, "modify the file `src/macos/ATDriverGenericMacOS/ATDriverGenericMacOSExtension/Common/Audio Unit/ATDriverGenericMacOSExtensionAudioUnit.swift`," however, that doesn't seem to be correct. There is no new voice listed after I applied the following change, cleaned the project, and ran the project again:
> 
> ```diff
> --- a/src/macos/ATDriverGenericMacOS/ATDriverGenericMacOSExtension/Common/Audio Unit/ATDriverGenericMacOSExtensionAudioUnit.swift       
> +++ b/src/macos/ATDriverGenericMacOS/ATDriverGenericMacOSExtension/Common/Audio Unit/ATDriverGenericMacOSExtensionAudioUnit.swift       
> @@ -167,7 +167,7 @@ public class ATDriverGenericMacOSExtensionAudioUnit: AVSpeechSynthesisProviderAu
>                  logger.log("speechVoices")
>              }
>              return [
> -            AVSpeechSynthesisProviderVoice(name: "ATDriverGenericMacOSExtensionVoice", identifier: "ATDriverGenericMacOSExtension", primaryLanguages: ["en-US"], supportedLanguages: ["en-US"])
> +            AVSpeechSynthesisProviderVoice(name: "ATDriverGenericMacOSExtensionVoice2", identifier: "ATDriverGenericMacOSExtension2", primaryLanguages: ["en-US"], supportedLanguages: ["en-US"])
>              ]
>          }
>          set { }
> ```
> 
> Can you be a little more specific?

You made the change I meant.

The change should should up in the dropdown for **System Settings > Accessibility > Spoken Content > System voice**.

![image](https://github.com/w3c/aria-at-automation-driver/assets/833298/d3d483b2-de30-4436-a29e-5b57df141ed0)

If there is still an item for the extension but its the old name, I think it could be recognizing a version of the extension is installed, and its using a cached copy of the list of voices that either has not yet updated or when it tried to update an error occured and it is reusing an older cache. I don't know if reuse of an old cache is possible. From my experience the cache gets updated in a manner of minutes after a new copy of the extension is installed.

2024-02-12 23:26 UTC, jugglinmike commented
> Oh. Interesting. Can you dump `log show --process ATDriverGeneric`?

Sure. I reverted [my temporary name change](https://github.com/w3c/aria-at-automation-driver/pull/32#issuecomment-1928668740), rebuilt, enabled it in the system settings, and typed `say hello` in a new Terminal session.

<details>
  <summary>log contents</summary>

    Timestamp                       Thread     Type        Activity             PID    TTL  
    2024-02-12 17:57:45.451811-0500 0x1ffdb    Activity    0x21610              5310   0    ATDriverGenericMacOS: (libsystem_secinit.dylib) AppSandbox
    2024-02-12 17:57:45.666218-0500 0x1ffdb    Activity    0x21611              5310   0    ATDriverGenericMacOS: (libsystem_info.dylib) Membership API: translate identifier
    2024-02-12 17:57:45.667017-0500 0x1ffdb    Activity    0x21612              5310   0    ATDriverGenericMacOS: (libsystem_containermanager.dylib) container_create_or_lookup_for_current_user
    2024-02-12 17:57:45.667021-0500 0x1ffdb    Activity    0x21613              5310   0    ATDriverGenericMacOS: (libsystem_containermanager.dylib) container_create_or_lookup_for_platform
    2024-02-12 17:57:45.667160-0500 0x1ffdb    Default     0x21613              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:xpc] Requesting container lookup; personaid = -1, type = NOPERSONA, name = <unknown>, origin [pid = 0, personaid = 0], proximate [pid = 0, personaid = 0], class = 2, identifier = <private>, group_identifier = <private>, create = 0, temp = 0, euid = 501, uid = 501
    2024-02-12 17:57:45.667170-0500 0x1ffdb    Activity    0x21614              5310   0    ATDriverGenericMacOS: (libsystem_containermanager.dylib) container_query_t
    2024-02-12 17:57:45.667191-0500 0x1ffdb    Default     0x21614              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:query] Query; personaid = -1, type = NOPERSONA, name = <unknown>, origin [pid = 0, personaid = 0], proximate [pid = 0, personaid = 0], euid = 501, uid = 501, query = <private>
    2024-02-12 17:57:45.669259-0500 0x1ffdb    Default     0x21613              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:unspecified] container_query_get_single_result: success
    2024-02-12 17:57:45.669294-0500 0x1ffdb    Default     0x21613              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:sandbox] Consuming sandbox extension; path = [<private>], key = 0
    2024-02-12 17:57:45.669295-0500 0x1ffdb    Activity    0x21615              5310   0    ATDriverGenericMacOS: (libsystem_containermanager.dylib) container_copy_object
    2024-02-12 17:57:45.669299-0500 0x1ffdb    Default     0x21615              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:sandbox] Consuming sandbox extension; path = [<private>], key = 0
    2024-02-12 17:57:45.669303-0500 0x1ffdb    Default     0x21613              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:sandbox] Revoking sandbox extension; key = 0
    2024-02-12 17:57:45.669304-0500 0x1ffdb    Default     0x21613              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:unspecified] container_create_or_lookup_for_platform: success
    2024-02-12 17:57:45.669306-0500 0x1ffdb    Default     0x21610              5310   7    ATDriverGenericMacOS: (libsystem_containermanager.dylib) [com.apple.containermanager:sandbox] Revoking sandbox extension; key = 0
    2024-02-12 17:57:45.676486-0500 0x1ffdb    Activity    0x21616              5310   0    ATDriverGenericMacOS: (libsystem_info.dylib) Retrieve User by ID
    2024-02-12 17:57:45.744152-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (AVFCapture) [com.apple.coremedia:] <<<< AVAUVoiceIOChatFlavor >>>> vpio_preferenceChangedListener: new value ((null)) for key AUVoiceIOClients/com-bocoup-ATDriverGenericMacOS/AUVoiceIOChatFlavor, translatedBundleID com.bocoup.ATDriverGenericMacOS, bundleIDs {(
        "com.bocoup.ATDriverGenericMacOS"
    )}
    2024-02-12 17:57:45.745408-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio)             HALSystem.cpp:119    Enabling HAL Voice Isolation support
    2024-02-12 17:57:45.746199-0500 0x1ffdb    Activity    0x21617              5310   0    ATDriverGenericMacOS: (TCC) TCCAccessRequest() IPC
    2024-02-12 17:57:45.758906-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio)   HALPlugInManagement.cpp:393    HALPlugInManagement::RegisterPlugIns: skipping in-process plug-ins
    2024-02-12 17:57:45.759534-0500 0x1ffdb    Error       0x0                  5310   0    ATDriverGenericMacOS: (CoreFoundation) [com.apple.CFBundle:plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000130c440> F8BB1C28-BAE8-11D6-9C31-00039315CD46
    2024-02-12 17:57:45.770151-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio)      HALC_ProxyObject.cpp:188    HALC_ProxyObject::GetPropertyDataSize ('<private>', '<private>', 0, AI32): got an error from the server, 0x77686F3F
    2024-02-12 17:57:45.770757-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio)      HALC_ProxyObject.cpp:469    HALC_ProxyObject::GetPropertyData ('<private>', '<private>', 0, DAI32): got an error from the server, 0x77686F3F
    2024-02-12 17:57:45.781922-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:399   AUHAL: (0x7fc303013a40) Selecting device 63 from constructor
    2024-02-12 17:57:45.781983-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:572   SelectDevice: -> (0x7fc303013a40)
    2024-02-12 17:57:45.782020-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:629   SelectDevice: (0x7fc303013a40) not already running
    2024-02-12 17:57:45.782051-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:704   SelectDevice: (0x7fc303013a40) nothing to teardown
    2024-02-12 17:57:45.782079-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:708   SelectDevice: (0x7fc303013a40) connecting device 63
    2024-02-12 17:57:45.782219-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:3110  IsDeviceUsable: (0x7fc303013a40) Device ID: 63 (Input:No | Output:Yes): true
    2024-02-12 17:57:45.782372-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:718   SelectDevice: (0x7fc303013a40) created ioproc 0xa for device 63
    2024-02-12 17:57:45.782405-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:1454  UpdateStreamFormats: -> (0x7fc303013a40)
    2024-02-12 17:57:45.782557-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]                 AUHAL.cpp:1518  UpdateStreamFormats: 
      output stream 0 [0x40]:  2 ch,  44100 Hz, Float32, interleaved
    2024-02-12 17:57:45.782600-0500 0x1ffdb    Default     0x0                  5310   0    ATDriverGenericMacOS: (CoreAudio) [com.apple.coreaudio:AUHAL]               [...]

2024-02-20 20:50 UTC, jugglinmike commented
@mzgoddard Although we got this running during our call on Friday, I'm now seeing the same error in response to `say`. This time, though, I'm a little more confident that I'm working with the latest code.

I can see just one extension installed:

>     $ mdfind ATDriverGenericMacOSExtension.appex
>     2024-02-19 15:46:55.144 mdfind[48021:467859] [UserQueryParser] Loading keywords and predicates for locale "en_US"
>     2024-02-19 15:46:55.145 mdfind[48021:467859] [UserQueryParser] Loading keywords and predicates for locale "en"
>     /Users/mike/Library/Developer/Xcode/DerivedData/ATDriverGenericMacOS-gnsaescpelxaewcragdkqcyxvdfw/Build/Products/Debug/ATDriverGenericMacOSExtension.appex

And after I use "Product > Clean Build Folder..." in Xcode, that extension is gone:

>     $ mdfind ATDriverGenericMacOSExtension.appex
>     2024-02-19 15:46:55.144 mdfind[48021:467859] [UserQueryParser] Loading keywords and predicates for locale "en_US"
>     2024-02-19 15:46:55.145 mdfind[48021:467859] [UserQueryParser] Loading keywords and predicates for locale "en"

...and it's likewise removed from the relevant dropdown in the System menu. After using "Product > Run" in Xcode and waiting about 20 seconds, the extension reappears in that dropdown. Selecting it and running `say` produces the error:

>     $ say hello
>     2024-02-19 16:01:17.102 say[48309:475641] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000032e94a0] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
>         "en-US"
>     ), Age: 0, Gender: 0, Size: 0, Version: (null)
>     2024-02-19 16:01:17.104 say[48309:475641] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000032e94a0] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
>         "en-US"
>     ), Age: 0, Gender: 0, Size: 0, Version: (null)
>     2024-02-19 16:01:17.105 say[48309:475641] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000032e94a0] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
>         "en-US"
>     ), Age: 0, Gender: 0, Size: 0, Version: (null)
>     2024-02-19 16:01:17.107 say[48309:475641] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000032e94a0] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
>         "en-US"
>     ), Age: 0, Gender: 0, Size: 0, Version: (null)
>     2024-02-19 16:01:17.107 say[48309:475641] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000032e94a0] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
>         "en-US"
>     ), Age: 0, Gender: 0, Size: 0, Version: (null)
>     2024-02-19 16:01:17.108 say[48309:475641] Could not retrieve voice [AVSpeechSynthesisProviderVoice 0x6000032e94a0] Name: ATDriverGenericMacOSExtensionVoice, Identifier: ATDriverGenericMacOSExtension, Supported Languages (
>         "en-US"
>     ), Age: 0, Gender: 0, Size: 0, Version: (null)

Any tips on what I should try next?

2024-02-20 22:27 UTC, mzgoddard commented
@jugglinmike If I recall correctly we also saw that error when you selected the pre-installed Eddy voice. If you delete our voice with `Clean Build Folder` and select the Eddy voice, does `say` produce that `Could not retrieve voice` error? I haven't seen that error personally so I'm less sure how to debug it but if the Eddy voice experiences the error without our voice installed, the error seems less likely to be related to our voice.

I remember I made a quick search for that error and saw https://forums.developer.apple.com/forums/thread/730789. That thread doesn't seem to have a solution for us and for them was likely more a bug?

I suspect its some kind of process permissions issue. (It kind of makes me think of bluetooth permissions issues for apps that are wrapped and crash.)

If I recall you ran it in tmux, can you try running it outside of tmux?

2024-02-21 03:39 UTC, jugglinmike commented
> @jugglinmike If I recall correctly we also saw that error when you selected the pre-installed Eddy voice. If you delete our voice with `Clean Build Folder` and select the Eddy voice, does `say` produce that `Could not retrieve voice` error? I haven't seen that error personally so I'm less sure how to debug it but if the Eddy voice experiences the error without our voice installed, the error seems less likely to be related to our voice.

Yup, same problem with Eddy.

> If I recall you ran it in tmux, can you try running it outside of tmux?

Yes! That was the problem! (I don't know which is more impressive: your perceptiveness or your creativity. I would not have consciously noted the presence of tmux, nor would I guess that it had anything to do with a problem like this. In any case, nice work.)

2024-02-21 03:40 UTC, jugglinmike approved these changes

2024-02-21 03:40 UTC, merged